### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by dietergeerts** [lakmeer/gulp-css-urlencode-inline-svgs#1]
Hi, could you plublish this to npm? It works, but I have my own npm module where I want to use it. Thx.

**Comment by lakmeer** [comment]
Hi,
I'm currently on holiday, if I get a chance to publish it I will, otherwise
I'm not back till September 5th.
Lak

**Comment by wernerkrauss** [comment]
still not on npm?

**Comment by lakmeer** [comment]
Sorry for the delay - this prompted me to finally work out why my npm auth
was failing. It is now fixed and this module has been pushed.

https://www.npmjs.com/package/gulp-css-urlencode-inline-svgs
